sudo: required
language: python
services:
  - docker
jobs:
  include:
    - stage:
      env: TOXENV=flake8
    - stage:
      env: TOXENV=py27
    - stage:
      env: TOXENV=py36
    - stage: deploy
      python: 3.6
      before_install: skip
      script: skip
      deploy:
        provider: pypi
        user: davehunt
        password:
          secure: GyTB/x+/F1DNmAWF4K8keaBgwUTq6AVgCfdMzArPSLiHxs4Fi98Y44U6YM4fy5qwZ8oJxYYwdlWoooStIYouV8PEg0GOl+x1m7eb02XXZEufVUqQ4p5sN3HHeUmj2Et0j0o0AkUvAZjY2zCS3hI9U8wH+rLrkyR/1g8a88HLeHo=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: mozilla/fxapom
cache:
  pip: true
before_install: docker build -t mozilla/fxapom .
install: skip
script: docker run -e TOXENV=$TOXENV mozilla/fxapom tox
